export const allAttributes = [
	"sl_no",
	"gender",
	"ssc_p",
	"ssc_b",
	"hsc_p",
	"hsc_b",
	"hsc_s",
	"degree_p",
	"degree_t",
	"workexp",
	"etest_p",
	"specialisation",
	"mba_p",
	"status",
	"salary",
];

export const translateAttribute = {
	sl_no: "Serial Number",
	gender: "Gender",
	ssc_p: "Secondary School Percentage",
	ssc_b: "Secondary School Board",
	hsc_p: "Higher Secondary Percentage",
	hsc_b: "Higher Secondary Board",
	hsc_s: "Higher Secondary Specialization",
	degree_p: "College Percentage",
	degree_t: "Field of education",
	workexp: "Work Experience",
	etest_p: "Employability Test Percentage",
	specialisation: "MBA Specialization",
	mba_p: "MBA Percentage",
	status: "Status of Employment",
	salary: "Salary after employment",
};
